#!/usr/bin/env bash
if ! test -d $HOME/.rbenv; then
    echo "[36mInstalling rbenv.[m"
    git clone git://github.com/sstephenson/rbenv.git $HOME/.rbenv
    mkdir -p $HOME/.rbenv/plugins
fi

if ! test -d $HOME/.rbenv/plugins/ruby-build; then
    echo "[36mInstalling rbenv: ruby-build.[m"
    mkdir -p $HOME/.rbenv/plugins
    git clone git://github.com/sstephenson/ruby-build.git $HOME/.rbenv/plugins/ruby-build
fi

if ! test -d $HOME/.rbenv/plugins/rbenv-gemset; then
    echo "[36mInstalling rbenv: rbenv-gemset.[m"
    mkdir -p $HOME/.rbenv/plugins
    git clone git://github.com/jamis/rbenv-gemset.git $HOME/.rbenv/plugins/rbenv-gemset
fi
