#!/usr/bin/env bash
if ! test -d $HOME/.plenv/.git; then
    echo "[36mInstalling plenv[m"
    git clone --depth 1 git://github.com/tokuhirom/plenv.git $HOME/.plenv
fi

if ! test -d $HOME/.plenv/plugins/perl-build; then
    mkdir -p $HOME/.plenv/plugins
    git clone --depth 1 git://github.com/tokuhirom/Perl-Build.git $HOME/.plenv/plugins/perl-build/
fi
