# zle.zsh: Configuration for the Z Line Editor

# Automatically generated by zkbd.
typeset -g -A key

key[F1]='^[[[A'
key[F2]='^[[[B'
key[F3]='^[[[C'
key[F4]='^[[[D'
key[F5]='^[[[E'
key[F6]='^[[17~'
key[F7]='^[[18~'
key[F8]='^[[19~'
key[F9]='^[[20~'
key[F10]='^[[21~'
key[F11]='^[[23~'
key[F12]='^[[24~'
key[Backspace]='^?'
key[Insert]='^[[2~'
key[Home]='^[[1~'
key[PageUp]='^[[5~'
key[Delete]='^[[3~'
key[End]='^[[4~'
key[PageDown]='^[[6~'
key[Up]='^[[A'
key[Left]='^[[D'
key[Down]='^[[B'
key[Right]='^[[C'
key[Menu]='^[[29~'

# Create some blank keymaps to play with.
bindkey -N sins .safe
bindkey -N scmd .safe

# Load required widgets
autoload insert-composed-char
autoload edit-command-line

zle -N edit-command-line
zle -N insert-composed-char

# Let the binding begin.
bindkey $key[Delete] delete-char
bindkey $key[Backspace] backward-delete-char

bindkey "" backward-delete-word
bindkey "[3^" delete-word

bindkey $key[Right] forward-char
bindkey $key[Left] backward-char

bindkey $key[Up] up-line-or-history
bindkey $key[Down] down-line-or-history

bindkey "^Q" push-line

bindkey "^A" beginning-of-line
bindkey "^E" end-of-line

bindkey "^N" backward-word
bindkey "^O" forward-word

bindkey "^S" history-incremental-search-forward
bindkey "^R" history-incremental-search-backward

bindkey "^V" quoted-insert

bindkey "^K" kill-line
bindkey "^U" kill-whole-line

bindkey "^I" expand-or-complete

bindkey "^L" clear-screen
bindkey "^K" insert-composed-char

bindkey "^X" execute-named-cmd

bindkey $key[F1] run-help
bindkey $key[F2] edit-command-line
